# Generated by Django 4.1.5 on 2023-01-14 15:35

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarNumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в имени!', regex='^[АВЕКМНОРСТУХ]\\d{3}(?<!000)[АВЕКМНОРСТУХ]{2}\\d{2,3}$')], verbose_name='Гос. номер')),
            ],
        ),
    ]
