# Generated by Django 4.1.5 on 2023-01-14 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumer',
            name='plate',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в номере!', regex='^[ABEKMHOPCTYX]\\d{3}(?<!000)[ABEKMHOPCTYX]{2}\\d{2,3}$')], verbose_name='Гос. номер'),
        ),
    ]
