# Generated by Django 4.1.5 on 2023-01-14 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_carnumer_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carnumer',
            name='plate',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимые символы в номере!', regex='^[ABEKMHOPCTYX]\\d{3}[ABEKMHOPCTYX]{2}$')], verbose_name='Гос. номер'),
        ),
    ]
