# Generated by Django 4.1.5 on 2023-01-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_carnumer_plate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carnumer',
            options={'verbose_name': 'Номер машины', 'verbose_name_plural': 'Номера машин'},
        ),
    ]
